### ISSUE TITLE
Installation fails on Debian Wheezy

### ISSUE THREAD

**Issue by finster-** [ucoin-io/ucoin_ynh#1]
The installation via gui fails and by terminal i get the following error:

   Executing script...
   + domain=xxx.xxx.xxx
   + port=9201
   + sync_node=metab.ucoin.io
   + sync_port=9201
   + salt='xxxxxx'
   + pwd='xxxxxxxxx'
   + sudo apt-get -y -qq install nodejs npm nodejs-legacy
   E: Package nodejs not found
   E: Package npm not found
   E: Package »nodejs-legacy« has no installation candidate
   + git clone https://github.com/ucoin-io/ucoin /tmp/ucoin
   Cloning into '/tmp/ucoin'...
   + sudo npm install -g /tmp/ucoin pm2
   sudo: npm: command not found
   + sudo yunohost app checkport 9201
   Success! Port 9201 is available
   + [[ ! 0 -eq 0 ]]
   + sudo yunohost firewall allow TCP 9201
    + ucoind config --noupnp --ipv4 --remote4 --remoteh xxx.xxx.xx --port 9201 --remotep 9201 --salt              'xxxxxxxxxxx' --passwd 'xxxxxxxxxxx'
   install: line 32: ucoind: command not found
   + ucoind sync metab.ucoin.io 9201
   install: line 34: ucoind: command not found
   + pm2 start /usr/bin/ucoind -- start
   install: line 37: pm2: command not found

**Comment by M5oul** [comment]
Thanks for testing. I have an issue to get IP address. When fixes, it will be ok.

**Comment by M5oul** [comment]
Sorry, but I won't support Debian Wheezy.
As uCoin will works with Node.js 4.x.x, and that [this version isn't very well supported](https://github.com/nodesource/distributions#installation-instructions) on Wheezy.

Furthermore, uCoin node software is still in developpement and will be ready may be when Wheezy will be deprecated.
