### ISSUE TITLE
NPM dependency

### ISSUE THREAD

**Issue by scith** [ucoin-io/ucoin_ynh#2]
Hi,
I didn't have npm and node installed so it created issues in the YunoHost package installation it seems:

```bash
+ cd /home/yunohost.app/ucoin
+ sudo npm install
sudo: npm: command not found
+ sudo npm install -g pm2
sudo: npm: command not found
+ sudo yunohost app checkport 8999
Success! Port 8999 is available
+ [[ ! 0 -eq 0 ]]
+ sudo yunohost firewall allow TCP 8999
+ node --harmony /home/yunohost.app/ucoin/bin/ucoind init --autoconf
install: line 40: node: command not found
```

It seems that "sudo apt-get install -y npm node" solved the issue.

Thanks

**Comment by M5oul** [comment]
I didn't had this issue. May be, I should uncomment this [line](https://github.com/ucoin-io/ucoin_ynh/blob/master/scripts/install#L37).

**Comment by M5oul** [comment]
Install script is using uCoin script.
