### ISSUE TITLE
Install from automatic script ?

### ISSUE THREAD

**Issue by scith** [ucoin-io/ucoin_ynh#3]
Je switche en français si ça te va :+1: 
J'ai pas réussi à faire fonctionner ton package YunoHost avec l'install script. On dirait que ça coince aux étapes "node --harmony" et "pm2" qui ne font rien ...

Par contre en faisant:
```bash
wget -qO- https://raw.githubusercontent.com/ucoin-io/ucoin/master/install.sh | bash
ucoind init --autoconfig
ucoind config --remoteh $domain --port $port --remotep $port --salt $salt --passwd $psswd # --cpu $cpu
ucoind sync $sync_node $sync_port
ucoind start
sudo yunohost service add ucoind --log /root/.config/ucoin/ucoin_default/ucoin.log
```

Ca semble marcher ... A peu près car mon "yunohost service" bugge sur "update-rc.d" et l'init script quand j'essaye de l'activer.
En tout cas la clé pour fixer mon install a été d'installer ucoind via le script bash (au lieu de compiler depuis la source) puis utiliser la commande ucoind au lieu d'ucoin.

Bizarre que ça ait marché chez toi du coup ? J'ai debian jessie aussi pourtant

Je suis toujours en couleur orange par contre dans la liste Network d'ucoin. Je ne sais pas ce que ça signifie ?

**Comment by M5oul** [comment]
Salut @scith,

Je te laisse lire et tester les dernières modifications que j’ai rapatriés de mon dépôt Gogs. L’installation devrait mieux fonctionner.

Je rencontre encore un soucis d’installation, le script passe de l’utilisateur `admin` à `root` et par conséquent change de dépôt de stockage des donnés et des configurations. Ceci empêche le démarrage du nœud.

Mon nœud uCoin je l’ai installé à la main, pas avec ce paquet, qui n’est pas encore fonctionnel.

Il y a une question à se poser sur la manière dont on installe les dépendances et uCoin.
Si on installe tout comme dans le paquet actuel ou si on utilise les scripts que tu as indiqué plus haut.

À l’avenir, je ferai mes commits ici. Car, Gogs ne permet pas encore les issues des personnes sans compte, de plus, YunoHost ne gère actuellement que les dépôts GitHub.

Dans Sakia, les nœuds en orange signifient qu’ils sont désynchronisés ou sur une autre branche.

**Comment by M5oul** [comment]
Je vais essayer dans une autre branche d’installer avec le script d’installation. Par contre, je ne suis pas sûr de savoir gérer le redémarrage de shell.

**Comment by M5oul** [comment]
J’ai switcher sur une installation avec le script d’installation de uCoin.
Tout est fonctionnel sauf le [démarrage du nœud](https://github.com/ucoin-io/ucoin_ynh/issues/5).
